name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@7f352e61cbe8130c957c3bc898c4fb025784ea1e
        with:
          xcode-version: latest-stable
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          echo "Scheme List JSON: $scheme_list"

          default=$(echo $scheme_list | ruby -e "require 'json'; data = JSON.parse(STDIN.read); puts data['workspace']['schemes'][0] if data['workspace'] && data['workspace']['schemes']")
          if [ -z "$default" ]; then
            echo "Error: No default scheme found."
            exit 1
          fi

          echo $default > default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          scheme=$(cat default)
          if [ -f *.xcworkspace ]; then
            filetype_parameter="workspace"
            file_to_build=$(ls *.xcworkspace)
		  else
            filetype_parameter="project"
            file_to_build=$(ls *.xcodeproj)
          fi

          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty
          exit ${PIPESTATUS[0]}
